### ISSUE TITLE
README errors

### ISSUE THREAD

**Issue by mroswell** [bennylope/pygeocodio#10]
The README example uses the coordinate (33.738987, -116.408) and mis-states the results in various places as 
'1600 Pennsylvania Ave, Washington, DC' or '100 Main St, Springfield, USA'

Someone needs to review the README pretty carefully. (I'm hoping that a careful proofing will also yield an answer to #9 )

**Comment by bennylope** [comment]
To clarify, is the issue that the example lat/long values don't correspond to the example addresses used to show how the functionality works?

> Someone needs to review the README pretty carefully.

Definitely appreciate the help if you'd like to volunteer!

**Comment by bennylope** [comment]
Closed by 53098427cea911e7ad271f93ff00ba7584f1710f
