### ISSUE TITLE
return legislative district,  and congressional district?

### ISSUE THREAD

**Issue by mroswell** [bennylope/pygeocodio#14]
Can pygeocodio be amended to return legislative district and congressional district?

**Comment by Goorzhel** [comment]
I'm having a hard time understanding this issue, if only because this worked for me:
```
Python 3.6.5 (default, Apr 27 2018, 21:02:20)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from geocodio import GeocodioClient
>>> from os import getenv
>>> from pprint import pprint
>>> client = GeocodioClient(getenv('API_KEY'))
>>> location = client.geocode("438 Geary, San Francisco", fields=["cd116"])
>>> pprint(location['results'][0]['fields'])
{'congressional_districts': [{'congress_number': '116th',
                              'congress_years': '2019-2021',
                              'district_number': 12,
                              'name': 'Congressional District 12',
                              'proportion': 1}]}
```
@mroswell, can you elaborate?

**Comment by rau** [comment]
@mroswell @Goorzhel I'm using geocodio right now - did you guys ever determine if this issue has been fixed?

@bennylope Is this still something that the help-wanted label applies to?

**Comment by Goorzhel** [comment]
@rau: I still can't tell what issue @mroswell is reporting. I demonstrated above that you only need two things: a US address, and `fields=cd116` or similar ([ref](https://www.geocod.io/docs/#fields)). Were I a maintainer, I'd close this as "not enough info".
