### ISSUE TITLE
UserWarning

### ISSUE THREAD

**Issue by mroswell** [bennylope/pygeocodio#15]
I'm working in a Jupyter notebook.

```
from geocodio import GeocodioClient
client = GeocodioClient('my_api_key')
```
yields this UserWarning:
```

/Users/mroswell/anaconda/lib/python2.7/site-packages/cffi/model.py:525: UserWarning: 'point_conversion_form_t' has no values explicitly defined; guessing that it is equivalent to 'unsigned int'
  % self._get_c_name())
```

**Comment by bennylope** [comment]
Don't think this is related to the pygeocodio library directly, possibly another dependency somewhere (https://stackoverflow.com/questions/36049690/cffi-userwarning-point-conversion-form-t-has-no-values-explicitly-defined)
