### ISSUE TITLE
How to extract LAT and LON separately from geocoded_location.coords?

### ISSUE THREAD

**Issue by dpsspatial** [bennylope/pygeocodio#16]
Hopefully an easy question, but is it possible to get a separate value for LON/X AND LAT/Y from the geocoded_location.coords object?

We're testing how, using python, the output coordinates can be dumped into a PostGIS database and assembled into a geometry object.

Thanks!

**Comment by bennylope** [comment]
`coords` is a tuple, so you can unpack just like so:

```python
lon, lat = data.coords
```

For PostGIS make sure you note the order. The [`Address` class](https://github.com/bennylope/pygeocodio/blob/c63c3e7c86c2a0ca17c2fbd273f346b8efea08d8/geocodio/data.py#L11) allows the order to be changed; by default these are returned `(lat, lon)` (hence the ordering in my example) but if you set the order to anything else the values will be returned `(lon, lat)`.

**Comment by dpsspatial** [comment]
Easy! Thank you!!!
