### ISSUE TITLE
Including a reference key in batch encoding

### ISSUE THREAD

**Issue by arashrez** [bennylope/pygeocodio#27]
Geocodio batch encoding allows for a reference key to be included if the request is submitted as a JSON object rather than a JSON array. See https://www.geocod.io/docs/#batch-geocoding

 Can this functionality be added?

**Comment by bennylope** [comment]
So as an alternative to sending the list with meaningful ordering, simply sending a dictionary with locally-referenceable keys (e.g. primary keys).

Yeah, I think this could be added! Did you want to take a crack at starting it?

**Comment by arashrez** [comment]
I'd love to, and I'll take a look at it, but my python experience is extremely limited as I mainly use different languages. Your library just happens to be a part of the first project I've ever programmed in python.
