### ISSUE TITLE
Error while calling the GeocodioClient

### ISSUE THREAD

**Issue by ayanchandra** [bennylope/pygeocodio#45]
Pasting the exact error here:

Traceback (most recent call last):
  File "main_new.py", line 21, in <module>
    from geocodio_util import *
  File "/home/ayan_chandra/services/forms-service/geocodio_util.py", line 1, in <module>
    from geocodio import GeocodioClient
  File "/home/ayan_chandra/anaconda3/lib/python3.7/site-packages/geocodio/__init__.py", line 9, in <module>
    from client import GeocodioClient
ModuleNotFoundError: No module named 'client'

I have installed the package by

pip install pygeocodio

**Comment by Unix-Code** [comment]
I don't see a line in the current version of this project that has `from client import GeocodioClient`, so I looked back across the version history, and it seems like that line is from, at latest, version 0.2.0, which is behind by many major versions. I'd highly recommend trying to upgrade to a newer version and trying again. 

You can upgrade the package to a newer version with:
`$ pip install [package_name] --upgrade` OR `$ pip install [package_name] -U`

Version 1.0.0 is the most recent (but it drops Python 2.7 support, if that's relevant)
Version 0.12.0 is the most up-to-date version compatible Python 2.7, if that's relevant.
