### ISSUE TITLE
Field name "census" raises a ValueError

### ISSUE THREAD

**Issue by ndingwall** [bennylope/pygeocodio#8]
"census" is one of the available fields: https://geocod.io/docs/#census-block-tract-amp-fips-codes, but calling client.geocode(address, fields=['census']) raises a ValueError ("census' is not a valid field value"). I fixed this locally by adding 'census' to ALLOWED_FIELDS on line 15 of client.py.

**Comment by bennylope** [comment]
This was closed in [v0.5.0](https://github.com/bennylope/pygeocodio/releases/tag/v0.5.0) which I finally managed to get uploaded successfully to PyPI.

**Comment by bennylope** [comment]
Thanks for reporting this!
