### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by mroswell** [bennylope/pygeocodio#9]
I get KeyErrors when I run the last two examples in the README
https://github.com/bennylope/pygeocodio

`locations.get("33.738987, -116.4083").formatted_address`
and
`locations.get((33.738987, -116.4083)).formatted_address`

**Comment by snake-plissken** [comment]
The key error is raised because of the space in the formatting string:

https://github.com/bennylope/pygeocodio/blob/master/geocodio/data.py#L117

The keys in LocationCollection.lookups have no spaces:

```
>>> locations.lookups
{u'33.738987,-116.4083': 2}
```

**Comment by bennylope** [comment]
Closed by c63c3e7c86c2a0ca17c2fbd273f346b8efea08d8

**Comment by snake-plissken** [comment]
Thanks Uncle Ben!
